config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"

  get 'home/about'

   # devise_for :users
        # controllers: {
      #     sessions:      'users/sessions',
      #     passwords:     'users/passwords',
      #     registrations: 'users/registrations'
      # }
  devise_for :users


  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :post_comments, only: [:create, :destroy]
  end

  resources :users do
   member do
     get :following, :followers
    end
  end
  
  get '/search', to: 'search#search'

  resources :relationships, only: [:create, :destroy]


end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @contants = params[:contants]
    @users_or_books = params[:option]
    @how_search = params[:choice]
    @record = search_for(@contants, @users_or_books, @how_search)

    if @users_or_books == "1"
      @users = @record
    else
      @books = @record
    end
  end

private

  def search_for(contants, users_or_books, how_search)
    if users_or_books == "1"
        if how_search == "1"
                User.where(['name LIKE ?', "%#{contants}%"])
        elsif how_search == "2"
                User.where(['name LIKE ?', "%#{contants}"])
        elsif how_search == "3"
                User.where(['name LIKE ?', "#{contants}%"])
        elsif how_search == "4"
                User.where(['name LIKE ?', "#{contants}"])
        else
                User.all
        end
    elsif users_or_books == "2"
        if how_search == "1"
            Book.where(['title LIKE ?', "%#{contants}%"])
        elsif how_search == "2"
            Book.where(['title LIKE ?', "%#{contants}"])
        elsif how_search == "3"
            Book.where(['title LIKE ?', "#{contants}%"])
        elsif how_search == "4"
            Book.where(['title LIKE ?', "#{contants}"])
        else
            Book.all
        end
     end
  end



end



#   def search
#     @model = params["search"]["model"]
#     @content = params["search"]["content"]
#     @how = params["search"]["how"]
#     @datas = search_for(@how, @model, @content)
#   end

#   private
#   def match(model, content)
#     if model == 'users'
#       User.where(name: content)
#     elsif model == 'books'
#       Book.where(title: content)
#     end
#   end

#   def forward(model, content)
#     if model == 'users'
#       User.where("name LIKE ?", "#{content}%")
#     elsif model == 'books'
#       Book.where("title LIKE ?", "#{content}%")
#     end
#   end

#   def backward(model, content)
#     if model == 'users'
#       User.where("name LIKE ?", "%#{content}")
#     elsif model == 'books'
#       Book.where("title LIKE ?", "%#{content}")
#     end
#   end

#   def partical(model, content)
#     if model == 'users'
#       User.where("name LIKE ?", "%#{content}%")
#     elsif model == 'books'
#       Book.where("title LIKE ?", "%#{content}%")
#     end
#   end

#   def search_for(how, model, content)
#     case how
#     when 'match'
#       match(model, content)
#     when 'forward'
#       forward(model, content)
#     when 'backward'
#       backward(model, content)
#     when 'partical'
#       partical(model, content)
#     end
#   end
# end

app/views/search/_form.html.erb
<%#= form_tag(search_path, :method => 'get') do %>
  <%#= text_field_tag 'contants' %>
  <%#= select_tag 'option', options_for_select({"user"=> "1","book"=>"2"})%>
  <%#= select_tag(:choice, options_for_select([["部分検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
  <%#= submit_tag '検索' %>
<%# end %>


  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= text_field_tag 'contants' %>
    <%= select_tag 'option', options_for_select({"user"=> "1","book"=>"2"})%>
    <%= select_tag(:choice, options_for_select([["部分検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
    <%= submit_tag '検索' %>
  <% end %>

app/views/search/search.html.erb
<!--<p>検索</p>-->
<!--<%#= form_tag(search_path,:method => 'get') do %>-->
<!--  <%#= text_field_tag :search %>-->
<!--  <%#= submit_tag 'Search', :name => nil %>-->
<!--<%# end %>-->

<!--<ul><%# @datas.each do |user| %>-->
<!--  <li>-->
<!--    <%#= link_to user.name, user %>-->
<!--    <%#= user.created_at %>-->
<!--    <%#= user.status %>-->
<!--  </li>-->
<!--  <%# end %>-->
<!--</ul>-->

<% if @users_or_books == "1"%>
    <h3>Users search for</h3>
    <table class="table table-striped">
        <tr>
            <th></th>
            <th>name</th>
        </tr>
        <% @users.each do |user| %>

            <tr>
                <th>
                <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
                </th>
                <th><%= link_to user.name , user_path(user.id) , class:'btn btn-link'%></th>
            </tr>

        <% end %>
    </table>

<% elsif @users_or_books == "2" %>
    <h3>Books search for</h3>
    <table class="table table-striped">
        <tr>
            <th></th>
            <th>title</th>
            <th>opinion</th>
        </tr>
    <% @books.each do |book| %>
            <tr>
                <th>
                 　 <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
                </th>
                <th><%= link_to book.title , book_path(book.id) , class:'btn btn-link' %></th>
                <th><%= book.body %></th>
            </tr>
    <% end %>
    </table>
<% else %>
<% end %>