config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"

  get 'home/about'

   # devise_for :users
        # controllers: {
      #     sessions:      'users/sessions',
      #     passwords:     'users/passwords',
      #     registrations: 'users/registrations'
      # }
  devise_for :users


  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :post_comments, only: [:create, :destroy]
  end

  resources :users do
   member do
     get :following, :followers
    end
  end
  
  get '/search', to: 'search#search'

  resources :relationships, only: [:create, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  # has_many :follower, class_name: "User", foreign_key: "follower_id", dependent: :destroy
  # has_many :followed, through: :follower, source: :

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  attachment :profile_image

  validates :name, presence: true , uniqueness: true , length: { minimum: 2 , maximum: 20}

  validates :introduction , length: { maximum: 50 }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    # flash[:complete]="Welcome! You have signed up successfully."
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
 
  def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    # flash[:notice]="Signed in successfully."
  end

  # DELETE /resource/sign_out
  def destroy
    super
    # flash[:complete]="Signed out successfully."
  end

  protected
  def configure_sign_in_params
        devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :ensure_correct_user , only: [:edit ,:update]

  def index
    @users =User.all
    @user =current_user
    @book =Book.new
  end


  def show
    @book =Book.new
    # @user = User.find(current_user.id)
    @user = User.find(params[:id])
    # @user =current_user
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
        # redirect_to user_path(@user)
  end

  def update
    @user = User.find(params[:id])
    # binding.pry

    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:complete]="You have updated user successfully."
    else
      render :edit
      flash[:complete]="Failed to save"
    end
  end
  
  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
  

  private
  
    def set_user
      @user = User.find([:id])
    end
  
    def user_params
      params.require(:user).permit(:name, :introduction,  :profile_image)
    end
    # def correct_user
    #   redirect_to(user_url) unless params[:id] == current_user.id
    #   # redirect_to(user_url) unless @user == current_user
    # end
  
    def ensure_correct_user
      @user = User.find_by(id:params[:id])
      if @user.id != current_user.id
        redirect_to("/users/#{current_user.id}")
      end
    end
    
    def zipedit
      params.require(:user).permit(:postcode, :prefecture_name, :address_city, :address_street, :address_building)
    end
    
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
 <% if @book.errors.any? %>
    <div id="error_explanation" class="error">
      <h2><%= pluralize(@book.errors.count, "error") %>
      prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% if user_signed_in? && user == current_user %>

<% end %>
  <h3>User info</h3>
<table class="table">
  <tr>
  <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"%>
  </tr>
  <tr>
  <td>name</td>
  <td><%= user.name %></td>
  </tr>
  <tr>
  <td>introduction</td>
  <td><%= user.introduction %></td>
  </tr>
  <tr>
  <td>follows</td>
  <td> 
    <%= link_to following_user_path(user) do %>
      <%= user.followings.count %>
    <% end %>
  </td>
  </tr>
  <tr>
  <td>followers</td>
  <td>
    <%= link_to followers_user_path(user) do %>
      <%= user.followers.count %>
    <% end %>
  </td>
  </tr>

  <td><%= render 'relationships/follow_button',user: user %></td>

</table>

<!--% if user_signed_in? && user == current_user %>-->
<%= link_to edit_user_path(user) do %>
<button type="button" class="btn btn-light btn-lg btn-block">
<i class="fas fa-user-cog"></i></button>
<% end %>



<!--% end %>-->

app/views/users/_stats.himl.erb
 <% user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">

                <% if @user.errors.any? %>
                <div id="error_explanation" class="error">
                  <h2><%= pluralize(@user.errors.count, "error") %>
                  prohibited this book from being saved:</h2>

                  <ul>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
                <% end %>

      <h3>User info</h3>
      <!--<table class="table">-->
      <!--%= @user.name %>-->

      <%= form_with model:@user, local:true do |f| %>
      <!--<h4>Name</h4>-->

      <label for="user_name">Name</label>
      </br>
      <%= f.text_field :name %>
      <!--<input class="form-control name" type="text" name="user[name]" id="user_name">-->
      </br>
      <label for="user_image">Image</label>
      <!--%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>-->
      </br>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </br>
      <label for="user_introduction">Introduction</label>
      </br>
      <%= f.text_area :introduction %>
      </br>
      <%= f.submit 'Update User', class:'btn btn-secondary' %>

      <% end %>
       <!--</table>-->
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
   <div class="col-md-3">
    <%= render 'users/list', user: @user %>
    <%= render 'books/list', book: @book %>

   </div>

   <div class="col-md-8 offset-md-1">
     <h3>Users</h3>
     <table class="table table-striped">
       <tr>
       <th>image</th>
       <th>name</th>
       <th></th>
       <th></th>
       <th></th>
       <th></th>
       <th></th>
       </tr>

       <% @users.each do |user|%>
       <tr>
       <td>
         <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
       </td>
       <td><%= user.name %></td>
       <td>フォロー数:<%= user.followings.count %></td>
       <td>フォロワー数:<%= user.followers.count %></td>
       <td><%= render 'relationships/follow_button',user: user %></td>
       <td><%= link_to "Show", user_path(user.id) , class:'btn btn-link' %></td>
       <th>

       </th>
       </tr>
       <% end %>
     </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="notice"><%= flash[:complete] %></div>

<div class="container">
  <div class="row">
      <div class="col-md-3">

        <%= render 'users/list', user: @user %>
        <%= render 'books/list', book: @book %>

      </div>

      <div class="col-md-8 offset-md-1">
       <h3>Books</h3>
          <table class="table table-striped">
            <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            </tr>

            <% @books.each do |book|%>
              <tr>
              <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x'%>
              <% end %>
              </td>
              <td><%= link_to book.title , book_path(book.id) , class:'btn btn-link' %></td>
              <td><%= book.body %></td>
               <td><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></td>
              </tr>
            <% end %>
          </table>
      </div>
  </div>
</div>

app/views/users/show_follow.html.erb
  <h3>Follows Users</h3>
  <table class="table table-striped">
       <tr>
       <th>image</th>
       <th>name</th>
       <th></th>
       <th></th>
       <th></th>
       </tr>
<% @user.followings.each do |user| %>
<tr>
  <td>
  <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
  </td>
  <td><%= user.name %> </td>
  <td>フォロー数:<%= user.followings.count %></td>
  <td>フォロワー数:<%= user.followers.count %></td>
  <td><%= link_to 'show', user_path(user) %></td>
</tr>

<% end %>
</table>

app/views/users/show_follower.html.erb
  <h3>Followers Users</h3>
  <table class="table table-striped">
       <tr>
       <th>image</th>
       <th>name</th>
       <th></th>
       <th></th>
       <th></th>
       </tr>
<% @user.followers.each do |user| %>
<tr>
  <td>
  <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
  </td>
  <td><%= user.name %> </td>
  <td>フォロー数:<%= user.followings.count %></td>
  <td>フォロワー数:<%= user.followers.count %></td>
  <td><%= link_to 'show', user_path(user) %></td>
</tr>

<% end %>
</table>