config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"

  get 'home/about'

   # devise_for :users
        # controllers: {
      #     sessions:      'users/sessions',
      #     passwords:     'users/passwords',
      #     registrations: 'users/registrations'
      # }
  devise_for :users


  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :post_comments, only: [:create, :destroy]
  end

  resources :users do
   member do
     get :following, :followers
    end
  end
  
  get '/search', to: 'search#search'

  resources :relationships, only: [:create, :destroy]


end

app/models/concerns/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end




  validates :title, presence: true
  validates :body, presence: true ,
                  length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!
 before_action :ensure_correct_user ,only: [:edit, :update]


  def index
    @books = Book.all
    @book =Book.new
    @user = current_user
    # @user = @book.user.page(params[:page]).reverse_order
    @users =User.all
  end

  def show
    @book = Book.find(params[:id])
    @bookn =Book.new
    @user = @book.user
    @users =User.all
    @post_comment = PostComment.new
  end


  def create
    @book =Book.new(book_params)
    @book.user_id =current_user.id
    if @book.save
     redirect_to book_path(@book.id)
     flash[:complete]="You have created book successfully."
    else
     @books = Book.all
     @user =current_user
     render :index
     flash[:complete]="Failed to save"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
       redirect_to book_path(@book)
       flash[:complete]="You have updated book successfully."
    else
       render :edit
       flash[:complete]="Failed to update"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:complete]="Book was successfully destroyed."
    redirect_to books_path
  end

#   def set_book
#     @book = current_user.books.find_by(id: params[:id])
#   end
  # helper_method :current_user, :logged_in?

 private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find_by(id:params[:id])
    if @book.user_id != current_user.id
      redirect_to("/books")
    end
  end
 end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<h2 class="mt-3">New book</h2>
<!-- form_with部分 -->
<%= form_with model:book, local:true do |f| %>

 <!--% if @book.errors.any? %>-->
 <!--   <div id="error_explanation" class="notice">-->
 <!--     <h2>%= pluralize(@book.errors.count, "error") %> -->
 <!--     prohibited this book from being saved:</h2>-->
 <!--     <ul>-->
 <!--       % @book.errors.full_messages.each do |message| %>-->
 <!--         <li>%= message %></li>-->
 <!--       % end %>-->
 <!--     </ul>-->
 <!--   </div>-->
 <!-- % end %>-->

  <h4>Title</h4>
  <%= f.text_field :title %>
  <!--<label for="book_title">Title</label>-->
  <!--<textarea class="form-control book_title" type="text" name="book[title]" id="book_title"></textarea>-->
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <!--<br>-->
  </br>
  <!--<label for="book_opinion">Opinion</label>-->
  <!--<textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>-->
  
  <%= f.submit 'Create Book', class:'btn btn-success' %>
  
<% end %>

app/views/books/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
             
                <% if @book.errors.any? %>
                <div id="error_explanation" class="error">
                  <h2><%= pluralize(@book.errors.count, "error") %>
                  prohibited this book from being saved:</h2>
            
                  <ul>
                    <% @book.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
                <% end %>
            
            <h1>Editing Book</h1>
            
            <%= form_with model:@book, local: true do |f| %>
              <h4>Title</h4>
              <%= f.text_field :title %>
              <h4>Body</h4>
              <%= f.text_area :body %>
              </br>
              <%= f.submit 'Update Book' , class:'btn btn-success' %>
              </br>
              <%= link_to "Show", book_path(@book), class:'btn btn-link' %>
              <%= link_to "Back", books_path, class:'btn btn-link' %>
              <% end %>
            
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>

app/views/books/index.html.erb
<!--<div class="alert alert-%= message_type %>"></div>-->
<div class="notice"><%= flash[:complete] %></div>


<div class="container">
<div class="row">
<div class="col-md-3">

<%= render 'users/list', user: @user %>
<%= render 'books/list', book: @book %>


</div>

<div class="col-md-8 offset-md-1">
 <h3>Books</h3>
  <table class="table table-striped">
  <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th></th>
  <th></th>
  </tr>

  <% @books.each do |book|%>
  <tr>
  <td>
  <%= link_to user_path(book.id) do %>
    <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
  <% end %>
  </td>

  <td><%= link_to book.title , book_path(book.id) , class:'btn btn-link' %></td>
  <td><%= book.body %></td>
      <th>
        <div id="favorites_buttons_<%= book.id %>">
         <%= render partial: 'favorites/favorite', locals: { book: book} %>
       </div>
      </th>


      <th>
       <p><%= link_to "#{book.post_comments.count} コメント", book_path(book.id) %></p>
      </th>
  </tr>
  <% end %>

  </table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="notice"><%= flash[:complete] %></div>

<div class="container">
<div class="row">
<div class="col-md-3">
<%= render 'users/list', user: @user %>
<%= render 'books/list', book: @bookn %>
</div>


<div class="col-md-8 offset-md-1">
<table class="table table-striped">
    <h3>Book detail</h3>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
        <th>
          <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40' %>
          </br>
          <%= link_to @user.name , user_path(@user.id) , class:'btn btn-link'%>
        </th>
        <th><%= link_to @book.title , book_path(@book.id) , class:'btn btn-link'%></th>
        <th><%= @book.body %></th>

      <th>
         <% if @book.favorited_by?(current_user) %>
           <p>
           <%= link_to book_favorites_path(@book), method: :delete do %>
            ♥<%= @book.favorites.count %> いいね
           <% end %>
           </p>
         <% else %>
           <p>
           <%= link_to book_favorites_path(@book), method: :post do %>
            ♡<%= @book.favorites.count %> いいね
           <% end %>
           </p>
         <% end %>
      </th>
      
      <th>
        
       <div id="comments_area">
        <%= render partial: 'post_comments/index', locals: { book: @book } %>
       </div>
      
       <div class="comment-create">
        <%= render partial: 'post_comments/post', locals: { book: @book, post_comment: @post_comment } %>
       </div>
        
      </th>

        <%  if current_user.id == @book.user_id %>
        <th><%= link_to "Edit", edit_book_path(@book) , class:'btn btn-success' %></th>
        <th><%= link_to "Destroy", book_path, method: :delete ,data:{ confirm:'Are you sure?'} , class:'btn btn-danger'%></th>
    　　<%  end %>


</table>
</div>
</div>
</div>