config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"

  get 'home/about'

   # devise_for :users
        # controllers: {
      #     sessions:      'users/sessions',
      #     passwords:     'users/passwords',
      #     registrations: 'users/registrations'
      # }
  devise_for :users


  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :post_comments, only: [:create, :destroy]
  end

  resources :users do
   member do
     get :following, :followers
    end
  end
  
  get '/search', to: 'search#search'

  resources :relationships, only: [:create, :destroy]


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TASK3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!--<nav class= "navbar navbar-expand-lg navbar-dark bg-dark"></nav>-->
      <header>
        <nav class= "navbar navbar-expand-lg navbar-dark bg-dark ">
          <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
            <!--<a class="navbar-brand justify-content-start">-->
            <!-- <span>Bookers</span>-->
             <!--%= link_to 'Bookers', root_path %>-->
            <!--</a>-->
            <div class="collapse navbar-collapse" id="navbarNavDropdown" >
            <ul class="navbar-nav ml-auto">
            
            <% if user_signed_in? %>
                <!--<div class="collapse navbar-collapse" id="navbarNavDropdown"></div>-->
                <!--<ul class="navbar-nav ml-auto justify-content-end ">-->
              <%= render 'search/form' %>
                <!--<a class="fas fa-home nav-link text-light" href="/users/:id}">Home</a>-->
              <%= link_to 'Home', user_path(current_user.id) ,class:'fas fa-home text-white' %>



                <!--<a class="fas fa-users nav-link text-light" href="/users">Users</a>-->
              <%= link_to 'Users', users_path ,class:'fas fa-users text-white'%>



                <!--<a class="fas fa-book-open nav-link text-light" href="/books">Books</a><-->
              <%= link_to 'Books', books_path , class:'fas fa-book-open text-white' %>



                <!--<a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">logout</a>-->
              <%= link_to 'logout', destroy_user_session_path, method: :delete , class:'fas fa-sign-out-alt text-white' %>


            <% else %>
                <!--<a class="fas fa-home nav-link text-light" href="/">Home</a>-->
              <%= link_to 'Home', root_path ,class:'fas fa-home text-white' %>



                <!--<a  href="/home/about">About</a>-->
              <%= link_to 'About', home_about_path ,class:"fas fa-link text-white" %>


                <!--<a class="fas fa-user-plus nav-link text-light" href="/users/sign_up">sign up</a>-->
              <%= link_to 'sign up', new_user_registration_path ,class:"fas fa-user-plus text-white" %>



                <!--<a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in">login</a>-->
              <%= link_to 'login', new_user_session_path ,class:"fas fa-sign-in-alt text-white" %>


            <% end %>
            </ul>
            </div>
          </div>
        </nav>
   </header>
  
        <body>
        <div class="open"><%= notice %></div>

        <%= yield %>
        </body>


<center> CopyRight Infratop.inc</center>



</html>